; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.25"

; Modules
projects[advanced_help][version] = "1.1"

projects[ctools][version] = "1.3"

projects[date][version] = "2.7"

projects[googlechat][version] = "1.x-dev"

projects[homebox][version] = "2.0-beta6"

projects[jquery_update][version] = "2.x-dev"

projects[panels][version] = "3.3"

projects[views][version] = "3.7"

projects[backup_migrate][version] = "2.8"
projects[] = backup_migrate_files
projects[] = media
projects[] = libraries

; Themes
projects[open_framework][type] = "theme"
projects[open_framework][download][type] = "git"
projects[open_framework][download][url] = "https://github.com/SU-SWS/open_framework.git"
projects[open_framework][download][branch] = "7.x-2.x"
projects[open_framework][download][revision] = "bceb9c47f6509ed18e2f174174ced2694d41b0c4"
