; This file was auto-generated by drush make
core = 7.x
api = 2
projects[drupal][version] = "7.x"

; Include Drupal.org dependencies
includes[] = "drupal-org.make"

; Themes
projects[open_framework][type] = "theme"
projects[open_framework][download][type] = "git"
projects[open_framework][download][url] = "https://github.com/SU-SWS/open_framework.git"
projects[open_framework][download][branch] = "7.x-2.x"
projects[open_framework][download][revision] = "bceb9c47f6509ed18e2f174174ced2694d41b0c4"

; ==========
; Libraries
; ==========

libraries[cytoscape.js][download][type] = get
libraries[cytoscape.js][download][url] = 'http://cytoscape.github.com/cytoscape.js/download/cytoscape.js-2.1.0.zip'
libraries[cytoscape.js][destination] = libraries
libraries[cytoscape.js][directory_name] = cytoscape.js
